name: linux

on:
  - push
  - pull_request

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.10'
          - '5.12'
          - '5.14'
          - '5.16'
          - '5.18'
          - '5.20'
          - '5.22'
          - '5.24'
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          curl -sL https://cpanmin.us/ | perl - -nq --with-develop --installdeps .
      - name: Run Tests
        run: prove -lr t
